
name: RelBot

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build
        run: |
          make checkver
          VERSION=$(grep ^EXT_VERSION Makefile | sed 's/.*= *//')
          echo "::set-env name=VERSION::${VERSION}"
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          tag_name: ${{github.ref}}
          release_name: ${{github.event.repository.name}} w${{env.VERSION}}
          body_path: docs/notes/v${{env.VERSION}}.md
          draft: false
          prerelease: false

